# Built with Jekyll 3.6.0

# Setup
title:               這裡是網站的總標題
tagline:             '這里寫的是tagline.'
description:         '這裡可以寫網站的描述。'
url:                 'https://caesitas-c.github.io'
baseurl:             '/blog'

# About/contact
author:
  name:              這是網站作者的名字
  url:               這裡可以填寫，也可以刪除這一行
  email:             這裡可以填寫，也可以刪除這一行

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  kojidan:
    output: true
    display: "古事談"
    category: 
      - "原生示例" 
      - "卷一"
  burning-your-boats:
    output: true
    display: "焚舟紀"
    category: 
      - "焚舟紀一" 
  kikigakisyou:
    output: true
    display: "聞書抄"
    category: 
      - "聞書抄一"
  kaleidoscope:
    output: true
    display: "鏡華錄"
    category: 
      - "鏡華錄一"
  
# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
